### ISSUE TITLE
Suggested optimizations / Triplets table up to word size 31

### ISSUE THREAD

**Issue by stefan-reich** [ArgosOfIthica/xorshift-brute-force#1]
Nice program, I can really use it as Iwant an XORSHIFT algorithm for any n, not just 8 or 16.

Just a small suggestion:

You could optimize it by simply stopping the loop in xor_shift_period as soon as a value is seen twice (testing for result[x] = 1), speeding up the program by at least a factor of 2 (or more? Haven't really done the math).

Oh, and you are testing 0 values for a, b and c which are not a possible result.

BTW here is [my Java version](https://code.botcompany.de/1035203) and [a table of working triplets](https://code.botcompany.de/1035196) up to word size 31. BTW I am allowing 0 in a triplet to indicate skipping one of the right xorshifts. This way we get faster RNGs, and we can include 1 and 2 bits.

**Comment by ArgosOfIthaca** [comment]
Sorry I didn't see this earlier, and thanks for the suggestion, I've implemented it as well as a few other optimizations I didn't bother adding when I wrote this years ago.
